project: 
  type: website
  output-dir: docs

website: 
  title: Relacyjne Systemy Organizacji Danych
  description: "Relacyjne Systemy Organizacji Danych dla studentów WAT w Warszawie"
  site-url: https://sebkaz-teaching.github.io/rsod
  sidebar:
    style: "docked" 
    contents:
      - index.qmd
      - section : "Wykłady"
        contents:
          - lectures/wyklad1.qmd
          # - lectures/wyklad2.qmd
          # - lectures/wyklad3.qmd
          # - lectures/wyklad4.qmd
      - section: "Ćwiczenia"
        contents:
          # - cwiczenia/cw1.ipynb
          # - cwiczenia/cw2.ipynb
          # - cwiczenia/cw3.ipynb
          # - cwiczenia/cw4.ipynb
          # - cwiczenia/cw5.ipynb
          # - cwiczenia/ml.ipynb
          # - cwiczenia/titanic.ipynb
  navbar:
    left:
          - href: ksiazki.qmd
            text: Książki
          
  page-footer: "Copyright 2025, Sebastian Zając"
format:
  html:
    page-layout: article
    css: style.css
    theme: cosmo
    toc: true
    toc-depth: 2
    toc-title: "**Sections**"
    self-contained-math: true
    code-overflow: wrap
    highlight-style: github-dark
    code-block-background: true
    link-external-newwindow: true